# Generated by Django 5.2.7 on 2025-10-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='average',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marks',
            name='isPass',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marks',
            name='total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
